import type { RouteType } from "@/types/routes";
import { lazy } from "react";

export const adminRoutes: RouteType[] = [
  {
    path: "/login",
    component: lazy(() => import("../views/admin-pages/login")),
    layout: "auth",
  },
  {
    path: "/404",
    component: lazy(() => import("../views/admin-pages/not-found")),
    layout: "auth",
  },
  {
    path: "/dashboard",
    component: lazy(() => import("../views/admin-pages/dashboard")),
    layout: "default",
    permission: "dashboard:read",
    group: "Main",
    label: "Dashboard",
    icon: lazy(() => import("../views/components/icons/Dashboard")),
  },
  {
    path: "/relationship-managers",
    component: lazy(() => import("../views/admin-pages/relationship-managers")),
    layout: "default",
    permission: "rm:read",
    group: "Main",
    label: "Relationship Managers",
    icon: lazy(() => import("../views/components/icons/RelationshipManager")),
  },
  {
    path: "/relationship-managers/add-rm",
    component: lazy(() => import("../views/admin-pages/relationship-managers/AddRmForm")),
    layout: "default",
    permission: "rm:create",
    group: "Children",
    label: "Add User",
  },
  {
    path: "/relationship-managers/edit-rm/:rmId",
    component: lazy(() => import("../views/admin-pages/relationship-managers/AddRmForm")),
    layout: "default",
    permission: "rm:update",
    group: "Children",
    label: "Edit User",
  },
  {
    path: "/relationship-managers/rm",
    component: lazy(() => import("../views/admin-pages/client-list/RmClientsPage")),
    layout: "default",
    permission: "rm:read",
    group: "Children",
    label: "RM",
  },
  {
    path: "/client-list",
    component: lazy(() => import("../views/admin-pages/client-list")),
    layout: "default",
    permission: "client:read",
    group: "Main",
    label: "Member List",
    icon: lazy(() => import("../views/components/icons/ClientList")),
  },
  {
    path: "/client-list/edit-client/:clientId",
    component: lazy(() => import("../views/admin-pages/client-list/EditClient")),
    layout: "default",
    permission: "client:update",
    group: "Children",
    label: "Edit Client",
  },
  {
    path: "/client-list/projects",
    component: lazy(() => import("../views/admin-pages/client-list/ClientProjects")),
    layout: "default",
    permission: "client:read",
    group: "Children",
    label: "Client Projects",
  },
  {
    path: "/client-list/projects/mci",
    component: lazy(() => import("../views/admin-pages/client-list/ProjectMCI")),
    layout: "default",
    permission: "client:read",
    group: "Children",
    label: "Project MCI",
  },
  {
    path: "/manage-parameters",
    component: lazy(() => import("../views/admin-pages/manage-parameters")),
    layout: "default",
    permission: "parameter:read",
    group: "Main",
    label: "Manage Parameters",
    icon: lazy(() => import("../views/components/icons/ManageParameters")),
  },
  {
    path: "/manage-parameters/client",
    component: lazy(() => import("../views/admin-pages/manage-parameters/ManageClientParameters")),
    layout: "default",
    permission: "parameter:read",
    group: "Children",
    label: "Manage Client Parameters",
  },
  {
    path: "/manage-parameters/client/edit-parameter/:editParamId",
    component: lazy(() => import("../views/admin-pages/manage-parameters/EditClientParameter")),
    layout: "default",
    permission: "parameter:update",
    group: "Children",
    label: "Edit Client Parameters",
  },
  {
    path: "/manage-parameters/client/edit-parameter/:parameterId/industry-map",
    component: lazy(() => import("../views/admin-pages/manage-parameters/IndustryMapView")),
    layout: "default",
    permission: "parameter:update",
    group: "Children",
    label: "Industry",
  },
  {
    path: "/manage-parameters/add-parameter",
    component: lazy(() => import("../views/admin-pages/manage-parameters/AddParameter")),
    layout: "default",
    permission: "parameter:create",
    group: "Children",
    label: "Add Parameter",
  },
  {
    path: "/manage-parameters/edit-parameter/:editParamId",
    component: lazy(() => import("../views/admin-pages/manage-parameters/AddParameter")),
    layout: "default",
    permission: "parameter:update",
    group: "Children",
    label: "Edit Parameter",
  },
  {
    path: "/manage-weightage",
    component: lazy(() => import("../views/admin-pages/manage-weightage")),
    layout: "default",
    permission: "weightage:read",
    group: "Main",
    label: "Manage Weightage",
    icon: lazy(() => import("../views/components/icons/ManageWeightage")),
  },
  {
    path: "/manage-weightage/industry",
    component: lazy(() => import("../views/admin-pages/manage-parameters")),
    layout: "default",
    permission: "manage-industry-weightage:page",
    group: "Children",
    label: "Manage Industry Weightage",
  },
  {
    path: "/manage-weightage/client",
    component: lazy(() => import("../views/admin-pages/manage-parameters")),
    layout: "default",
    permission: "manage-industry-weightage:page",
    group: "Children",
    label: "Manage Client Weightage",
  },
  {
    path: "/profile",
    component: lazy(() => import("../views/admin-pages/profile")),
    layout: "other",
    permission: "user:read",
    group: "Main",
    label: "Profile",
  },
];